### PR TITLE
Throw ArgumentError when null serviceUri specified

### LINKED ISSUE #227: The getter 'pathSegments' was called on null.
```
   flutter test --coverage
```
```
unhandled error during test:
    /Users/zoechi/dart/customers/lookatyou/lookatmybaby/lookatmybaby_flutter/test/widgets/drawer/menu_item/menu_item_test.dart
    NoSuchMethodError: The getter 'pathSegments' was called on null.
    Receiver: null
    Tried calling: pathSegments
    #0      Object.noSuchMethod (dart:core/runtime/libobject_patch.dart:46:5)
    #1      collect (package:coverage/src/collect.dart:16:33)
    <asynchronous suspension>
    #2      CoverageCollector.collectCoverage (package:flutter_tools/src/test/coverage_collector.dart:59:45)
    <asynchronous suspension>
    #3      CoverageCollector.onFinishedTest (package:flutter_tools/src/test/coverage_collector.dart:27:11)
    <asynchronous suspension>
    #4      _FlutterPlatform._startTest (package:flutter_tools/src/test/flutter_platform.dart:611:29)
    <asynchronous suspension>
    #5      _FlutterPlatform.loadChannel (package:flutter_tools/src/test/flutter_platform.dart:367:36)
    #6      PlatformPlugin.load (package:test/src/runner/plugin/platform.dart:65:19)
    <asynchronous suspension>
    #7      Loader.loadFile.<anonymous closure> (package:test/src/runner/loader.dart:248:36)
    <asynchronous suspension>
    #8      new LoadSuite.<anonymous closure>.<anonymous closure> (package:test/src/runner/load_suite.dart:89:31)
    <asynchronous suspension>
    #9      invoke (package:test/src/utils.dart:242:5)
    #10     new LoadSuite.<anonymous closure> (package:test/src/runner/load_suite.dart:88:7)
    #11     Invoker._onRun.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:test/src/backend/invoker.dart:403:25)
    <asynchronous suspension>
    #12     new Future.<anonymous closure> (dart:async/future.dart:174:37)
    #13     StackZoneSpecification._run (package:stack_trace/src/stack_zone_specification.dart:209:15)
    #14     StackZoneSpecification._registerCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:119:48)
    #15     _rootRun (dart:async/zone.dart:1122:38)
    #16     _CustomZone.run (dart:async/zone.dart:1023:19)
    #17     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
    #18     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965:23)
    #19     StackZoneSpecification._run (package:stack_trace/src/stack_zone_specification.dart:209:15)
    #20     StackZoneSpecification._registerCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:119:48)
    #21     _rootRun (dart:async/zone.dart:1126:13)
    #22     _CustomZone.run (dart:async/zone.dart:1023:19)
    #23     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:949:23)
    #24     Timer._createTimer.<anonymous closure> (dart:async/runtime/libtimer_patch.dart:21:15)
    #25     _Timer._runTimers (dart:isolate/runtime/libtimer_impl.dart:382:19)
    #26     _Timer._handleMessage (dart:isolate/runtime/libtimer_impl.dart:416:5)
    #27     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:165:12)
    
    00:44 +147 ~1: ... golden default style baby_profile_edit_screen.golden.default_style.my_text_message.lightBlue
    00:44 +147 ~1 -1: loading /Users/zoechi/dart/customers/lookatyou/lookatmybaby/lookatmybaby_flutter/test/widgets/drawer/menu_item/menu_item_test.dart [E]
      NoSuchMethodError: The getter 'pathSegments' was called on null.
      Receiver: null
      Tried calling: pathSegments
      package:flutter_tools/src/test/flutter_platform.dart 652:7   _FlutterPlatform._startTest
      ===== asynchronous gap ===========================
      dart:async/future_impl.dart 22:43                            _Completer.completeError
      dart:async/runtime/libasync_patch.dart 40:18                 _AsyncAwaitCompleter.completeError
      package:flutter_tools/src/test/flutter_platform.dart         _FlutterPlatform._startTest
      ===== asynchronous gap ===========================
      dart:async/zone.dart 1055:19                                 _CustomZone.registerUnaryCallback
      dart:async/runtime/libasync_patch.dart 77:23                 _asyncThenWrapperHelper
      package:flutter_tools/src/test/flutter_platform.dart         _FlutterPlatform._startTest
      package:flutter_tools/src/test/flutter_platform.dart 367:36  _FlutterPlatform.loadChannel
      package:test/src/runner/plugin/platform.dart 65:19           PlatformPlugin.load
      ===== asynchronous gap ===========================
      dart:async/zone.dart 1055:19                                 _CustomZone.registerUnaryCallback
      dart:async/runtime/libasync_patch.dart 77:23                 _asyncThenWrapperHelper
      package:test/src/runner/loader.dart                          Loader.loadFile.<fn>
      package:test/src/runner/load_suite.dart 89:31                new LoadSuite.<fn>.<fn>
      ===== asynchronous gap ===========================
      dart:async/zone.dart 1047:19                                 _CustomZone.registerCallback
      dart:async/zone.dart 964:22                                  _CustomZone.bindCallbackGuarded
      dart:async/timer.dart 52:45                                  new Timer
      dart:async/timer.dart 87:9                                   Timer.run
      dart:async/future.dart 172:11                                new Future
      package:test/src/backend/invoker.dart 402:15                 Invoker._onRun.<fn>.<fn>.<fn>
  ```

```
[✓] Flutter (Channel master, v0.5.8-pre.127, on Mac OS X 10.13.6 17G65, locale en-AT)
    • Flutter version 0.5.8-pre.127 at /Users/zoechi/flutter/flutter
    • Framework revision da0e898da9 (11 hours ago), 2018-07-25 01:39:23 +0200
    • Engine revision 95e91e31fa
    • Dart version 2.0.0-dev.69.0.flutter-937ee2e8ca

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /usr/local/opt/android-sdk
    • Android NDK at /usr/local/opt/android-sdk/ndk-bundle
    • Platform android-27, build-tools 27.0.3
    • ANDROID_HOME = /usr/local/opt/android-sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.4.1, Build version 9F2000
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 23.1.2
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] IntelliJ IDEA Ultimate Edition (version 2018.1.6)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 26.0.2
    • Dart plugin version 181.4892.1

[✓] Connected devices (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 8.1.0 (API 27) (emulator)

• No issues found!
```
  
I got this exception only once on my local machine (OSX).
The same command finished without problems in Travis.
It succeeded when I run it again.

If you don't see anything actionable feel free to just close.

### PR DESCRIPTION
**Pull request by cbracken**
If a null serviceUri is passed to the collect() function, throw
ArgumentError. Flutter's coverage collection infra previously had a bug
wherein a null observatory port URL was sometimes passed to this
function. This makes debugging such cases marginally easier.

Fixes #227.

### CODE REVIEW

**Comment by cbracken** [comment]
Fixes #227.

File: lib/src/collect.dart [hunk 1]
```diff
@@ -12,6 +12,9 @@ const _retryInterval = const Duration(milliseconds: 200);
 Future<Map<String, dynamic>> collect(
```
Comment (mklim) [inline lib/src/collect.dart]: Would it be worth documenting this and saying that `serviceUri` needs to be non-null?

Comment (cbracken) [reply lib/src/collect.dart]: Definitely! Done.
