### PR TITLE
Fix handling of part files in function coverage

### LINKED ISSUE #399: Function coverage can't handle part files
When `_processFunction` is called for a function defined in a part file, it searches for the token pos to line mapping in the root file of the library.

Related to #389

### PR DESCRIPTION
**Pull request by liamappelbe**
The current logic looks up the script's library, then looks up all the functions in the library, and assumes that all those functions are in the script. But part files break this assumption.

So instead we have to look up the library, then for each of its functions, look up the corresponding script, and insert the function into that script's hitmap. Caching means that this isn't any slower.

Fixes #399

### CODE REVIEW

File: lib/src/collect.dart [hunk 1]
```diff
@@ -271,22 +306,12 @@ Future<void> _processFunction(VmService service, IsolateRef isolateRef,
       }
       return;
     }
+    final hits = getHitMap(Uri.parse(script.uri!));
+    hits.funcHits ??= <int, int>{};
+    hits.funcNames ??= <int, String>{};
```
Comment (kevmoo) [inline lib/src/collect.dart:311]: nit. You *could* merge these lines.

```suggestion
    (hits.funcNames ??= <int, String>{})[line] = funcName;
```

🤷  – get rid of a null assert.

**Review by kevmoo — APPROVED** [review]
