### PR TITLE
Fix branch coverage test

### LINKED ISSUE #392: CI failing
https://github.com/dart-lang/coverage/actions/runs/2481699515

### PR DESCRIPTION
**Pull request by liamappelbe**
The Dart VM fix for the CI failures also means that some branch coverage cases are no longer skipped. So we get an extra branch hit in this test.

Fixes #392

### CODE REVIEW

File: test/collect_coverage_test.dart [hunk 1]
```diff
@@ -166,8 +166,18 @@ void main() {
...
-    expect(isolateFile?.branchHits,
-        {11: 1, 12: 1, 15: 0, 19: 1, 23: 1, 28: 1, 32: 0, 38: 1, 42: 1});
+    expect(isolateFile?.branchHits, {
+      11: 1,
+      12: 1,
+      15: 0,
+      19: 1,
+      23: 1,
+      28: 1,
+      if (platformVersionCheck(2, 18)) 29: 1,
```
Comment (kevmoo) [inline test/collect_coverage_test.dart:176]: This feature is SOOO NICE! @munificent

**Review by natebosch — APPROVED** [review]
